### ISSUE TITLE
Thank you for sharing this project

### ISSUE THREAD

**Issue by Irwin1985** [ktconnolly/monkey-interpreter#1]
Hi ktconnolly, I just wanna say thank you for sharing this project. I'm learning a lot of python (I'm a begginer at this language) thanks to your very clean implementation of the monkey language. I implemented monkey language few month ago but the concept didn't "clic" in my head because of the go language. It's turns out really difficult learning this kind of concepts by implementing it in a type safe language like go and alike.

Now python is showing me the smooth way with my second implementation and I can see and fill all gaps I left behind.

I also followed the [Ruslan's blog](https://ruslanspivak.com/lsbasi-part1/) which helped me to grasp the big picture of writing and implementing interpreters.

what about you? did you learn a lot by implementing Monkey lang? Are you new at this topic like me?

regards!

**Comment by ktconnolly** [comment]
Glad you found it useful! yeah I'm pretty new to the topic as well.  I also found that blog post quite useful and along with doing this project.

Thanks
